[environment]
max_requests = 35
receive_email_list = [ "openpicklabs@hotmail.com",]

[project]
name = "picker-python-project"
version = "0.1.0"
description = "Picker startup template for python project."
author = "openpick"
email = "openpicklabs@hotmail.com"
license = "MIT"

[task]
id = "b7e3a5d1-2c4f-41a7-b9d5-6a3c2b8d1e4f"
name = "Picker Python task"
status = "Idle"
installed = "240128"
runs = 128
last_run = "240301"

[environment.emailSettings]
smtpServer = "smtp.qq.com"
smtpPort = 587
enableSsl = true
senderEmail = ""
senderPassword = ""
subject = "Picker Python Project Task Manager Daily Report"
